const coinData = [
  {
    emperorId: 1,
    emperorName: "Caesar Augustus",
    wikiLink: "https://en.wikipedia.org/wiki/Augustus",
    fullName: "Imperator Caesar Augustus",
    birthName: "Gaius Octavius",
    bornDied: "63 BC - AD 14",
    reigned: "27 BC - AD 14",
    yearsReigned: 40,
    howDied: "natural causes / old age",
    notableFor: [
      "First emperor",
      "Ended Roman civil war when he defeated his rival Marcus Antony and his ally and lover Cleopatra",
      "Funded numerous major building projects around Rome",
    ],
    coinFile: ["assets/01-Aug37A.jpg", "assets/01-Aug37A_rev.jpg"],
    coinLink: "http://numismatics.org/ocre/id/ric.1(2).aug.31",
  },
  {
    emperorId: 2,
    emperorName: "Tiberius",
    wikiLink: "https://en.wikipedia.org/wiki/Tiberius",
    fullName: "Tiberius Caesar Augustus",
    birthName: "Tiberius Claudius Nero",
    bornDied: "42 BC - AD 37",
    reigned: "AD 14 - 37",
    yearsReigned: 22,
    howDied: "natural causes / old age",
    notableFor: [
      "Accomplished general",
      "Luxurious retreat on island of Capri",
      "Manipulated by Sejanus, captain of the praetorian guard",
    ],
    coinFile: ["assets/02-Tiberius27.jpg", "assets/02-Tiberius27_rev.jpg"],
    coinLink: "http://numismatics.org/ocre/id/ric.1(2).tib.18",
  },
  {
    emperorId: 3,
    emperorName: "Caligula",
    wikiLink: "https://en.wikipedia.org/wiki/Caligula",
    fullName: "Gaius Caesar Augustus Germanicus",
    birthName: "Gaius Julius Caesar",
    bornDied: "AD 12 - 41",
    reigned: "AD 37 - 41",
    yearsReigned: 3.5,
    howDied: "stabbed by his soldiers",
    notableFor: [
      "Known for his extravagance and cruelty",
      "Really loved chariot racing",
      "Rumored to have incestuous relationship with his sister",
    ],
    coinFile: ["assets/03-Caligula32.jpg", "assets/03-Caligula32_rev.jpg"],
    coinLink: "http://numismatics.org/ocre/id/ric.1(2).gai.32",
  },
  {
    emperorId: 4,
    emperorName: "Claudius",
    wikiLink: "https://en.wikipedia.org/wiki/Claudius",
    fullName: "Tiberius Claudius Caesar Augustus Germanicus",
    birthName: "Tiberius Claudius Nero Germanicus",
    bornDied: "10 BC - AD 54",
    reigned: "AD 41 - 54",
    yearsReigned: 13,
    howDied: "poisoned",
    notableFor: [
      "Accepted non-Italians into the Senate",
      "Launched invasion of Britain",
      "Wrote histories of Carthage and the Etruscans",
    ],
    coinFile: ["assets/04-Claudius25.jpg", "assets/04-Claudius25_rev.jpg"],
    coinLink: "http://numismatics.org/ocre/id/ric.1(2).cl.25",
  },
  {
    emperorId: 5,
    emperorName: "Nero",
    wikiLink: "https://en.wikipedia.org/wiki/Nero",
    fullName: "Nero Claudius Caesar Augustus Germanicus",
    birthName: "Lucius Domitius Ahenobarbus",
    bornDied: "AD 37 - 68",
    reigned: "AD 54 - 68",
    yearsReigned: 13,
    howDied: "suicide / ordered his secretary to stab him",
    notableFor: [
      "Famous for singing and performing on stage",
      "Kicked his pregnant mistress to death",
      "Last of the Julio-Claudian dyansty",
    ],
    coinFile: ["assets/05-Nero137.jpg", "assets/05-Nero137_rev.jpg"],
    coinLink: "http://numismatics.org/ocre/id/ric.1(2).ner.137",
  },
];

export default coinData;
