const coinData = [
  {
    emperorId: 1,
    emperorName: "Caesar Augustus",
    fullName: "Imperator Caesar Augustus",
    birthName: "Gaius Octavius",
    bornDied: "63 BC - AD 14",
    reigned: "27 BC - AD 14",
    yearsReigned: 40,
    howDied: "natural causes / old age",
    notableFor: [
      "First emperor",
      "Ended Roman civil war when he defeated his rival Marcus Antony and his ally and lover Cleopatra",
      "Funded numerous major building projects around Rome",
    ],
    coinFile: ["assets/01-Aug37A.jpg", "assets/01-Aug37A_rev.jpg"],
    URL: "http://numismatics.org/ocre/id/ric.1(2).aug.31",
  },
  {
    emperorId: 2,
    emperorName: "Tiberius",
    fullName: "Tiberius Caesar Augustus",
    birthName: "Tiberius Claudius Nero",
    bornDied: "42 BC - AD 37",
    reigned: "AD 14 - 37",
    yearsReigned: 22,
    howDied: "natural causes / old age",
    notableFor: [
      "Accomplished general",
      "Luxurious retreat on island of Capri",
      "Manipulated by Sejanus, captain of the praetorian guard",
    ],
    coinFile: ["assets/02-Tiberius27.jpg", "assets/02-Tiberius27_rev.jpg"],
    URL: "http://numismatics.org/ocre/id/ric.1(2).tib.18",
  },
  {
    emperorId: 3,
    emperorName: "Caligula",
    fullName: "Gaius Caesar Augustus Germanicus",
    birthName: "Gaius Julius Caesar",
    bornDied: "AD 12 - 41",
    reigned: "AD 37 - 41",
    yearsReigned: 3.5,
    howDied: "assassinated",
    notableFor: [
      "son of Germanicus, Tiberius's nephew",
      "known for his extravagance and cruelty",
      "really loved chariot racing",
    ],
    coinFile: ["", ""],
    URL: "",
  },
];

export default coinData;
